[package]
name = "like"
version = "0.1.0"
edition = "2021"

[dependencies]
memchr = "2.7.4"

[dev-dependencies]
proptest = "1.6.0"
criterion = "0.5.1"
regex = "1.11.1"

[[bench]]
name = "bench"
harness = false
