[package]
name = "like"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-set = "0.8.0"
itertools = "0.14.0"
memchr = "2.7.4"
rustc-hash = "2.1.0"

[dev-dependencies]
proptest = "1.6.0"
criterion = "0.5.1"
regex = "1.11.1"

[[bench]]
name = "bench"
harness = false
